	SUBROUTINE MODEL(DUR,IELM,ILR,ISR,IXS,PHI,QA,HZ)


C
C	THIS SUBROUTINE COMPUTES THE PARAMETERS OF THE
C	OBSERVATION STATE TRANSITION MATRIX PHI, THE
C	MEASUREMENT MATRIX, AND THE COVARIANCES.
C
C	VARIABLES:
C		DUR-	INPUT ELEMENT DURATION
C		IELM-	INPUT ELEMENT TYPE
C		ILR-	INPUT SAVED RATE
C		ISR-	INPUT RATE OF NEW STATE
C		IXS-	INPUT KEYSTATE OF NEW STATE
C
C		PHI-	OUTPUT STATE TRANSITION MATRIX ENTRY FOR
C			SIGNAL AMPLITUDE STATE
C		QA-	OUTPUT COVARIANCE FOR AMPLITUDE STATE
C		HZ-	OUTPUT MEASUREMENT MATRIX VALUE 
C


C	COMPUTE MEASUREMENT COEFFICIENT:

		HZ=IXS
		
C	COMPUTE PHI AND AMPLITUDE STATE VARIANCE (Q):

		R1=1200./ILR
		BAUDS=DUR/R1
		IF (BAUDS.GE.14.) BAUDS=14.

		IF(IELM.GE.3) GO TO 100
		QA=.0001
		PHI=1.
		GO TO 300

100		IF(IXS.EQ.0) GO TO 200
		PHI=1.
		QA=0.15*EXP(0.6*(BAUDS-14.))
		QA=QA+.01*BAUDS*EXP(.2*(1.-BAUDS))
		GO TO 300

200		XSAMP=22.4*R1
		PHI=10.**(-2/XSAMP)
		IF(BAUDS.GE.14.) PHI=1.
		QA=0.

300		RETURN
		END
