	SUBROUTINE PTRANS (KELEM, IRATE, LAMBDA, ILRATE, PTRX, PSUM,PIN,N)


C	THIS FUNCTION SUBROUTINE RETURNS THE PATH CONDITIONAL TRANSITION  
C	PROBABILITIES TO EACH ALLOWABLE STATE N.
C	VARIABLES:
C	KELEM-      INPUT CURRENT ELEMENT STATE
C	IRATE-      INPUT CURRENT DATA RATE STATE
C	LAMBDA-     INPUT IDENTITY OF CURRENT LTR STATE
C	PTRX-       INPUT KEYSTATE TRANSITION PROBABILITY
C	ELEMTR-     ELEMENT TRANSITION PROBABILITY MATRIX
C	
C	FUNCTION SUBROTINE USED:
C	SPDTR-      RETURNS DATA RATE TRANSITION PROBS,CONDITIONED ON CURRENT SPACE TYPE.
C	

	DIMENSION IELMST(400),ILAMI(16),ELEMTR(16,6)
	DIMENSION ILAMX(6),PIN(30)

	COMMON /BLKLAM/ IELMST,ILAMI,ILAMX
	COMMON /BLKELM/ ELEMTR

C	IF THE SAVED ELEMENT AND THE ELEMENT OF THE STATE
C	N TO WHICH THE PATH IS BEING EXTENDED ARE THE
C	SAME, THEN THE STATE TRANS PROB IS SIMPLY
C	KEYSTATE TRANS PROB:
C	

	IF(KELEM .NE. ILAMI(IELMST(LAMBDA))) GO TO 100
	PIN(N)=PTRX
C	HOWEVER, IF CURRENT DATA RATE STATE  = 3, THEN TRANS PROB = 0 ... WHY ? 
	IF(IRATE .NE. 3) PIN(N)=0.
	GO TO 200

C	OTHERWISE:
C	OBTAIN ELEM TRANS PROBS TABLE:
C	
100	PELEM=ELEMTR(IELMST(LAMBDA),KELEM)

C	NEXT COMPUTE ELEM-CONDITIONAL SPEED TRANS PROB:

	PRATE=SPDTR(IRATE,ILRATE,KELEM,ILAMI(IELMST(LAMBDA)))

C	TRANS IS THE PRODUCT: 

	PIN(N)=(1.-PTRX)*PELEM*PRATE
200	PSUM=PSUM+PIN(N)

C	PRINT 50, N, KELEM, IRATE, ILAMI(IELMST(LAMBDA)), PIN(N), PTRX, PELEM, PRATE, PSUM
C50	FORMAT(1X,'PTRANS:',4(I3,2X),5(F8.3,2X))
	RETURN
	END
