	SUBROUTINE LIKHD(Z,RN,IP,LAMBDA,DUR,ILRATE,P,LKHD)

C
C	THIS SUBROUTINE CALCULATES,FOR EACH PATH
C	EXTENSION TO STATE N, THE LIKELIHOOD OF THAT
C	TRANSITION GIVEN THE MEASUREMENTZ. IT USES
C	AN ARRAY OF LINEAR (KALMAN) FILTERS TO DO SO.
C
C	VARIABLES:
C	Z- INPUT MEASUREMENT
C	BN-INPUT NOISE POWER ESTIMATE
C	IP-INPUT SAVED PATH IDENTITY
C	LAMBDA-INPUT SAVED LTR STATE IDENTITY
C	DUR-INPUT SAVED DURATION OF ELEMENT ON PATH IP
C	ILRATE-INPUT SAVED DATA RATE (SPEED)
C	P-INPUT TRANSITION PROSABILITIES
C	SBHD-OUTPUT COMPUTED LIKELIHOODS FOR EACH TRANS
C
C  SUBRODTINES USED:
C	KALFIL-KALMAN FILTER FOR EACH NEW PATH
C

	REAL LKHD,LKHDJ
	DIMENSION P(25,30),LKHD(750)
	DIMENSION IELMST(400), ILAMI(16),ILAMX(6)
	DIMENSION ISX(6)

	COMMON/BLKLAM/IELMST,ILAMI,ILAMX
	COMMON/BLKS/ISX

C   OBTAIN SAVED KEYSTATE:
	IF (LAMBDA .EQ. 0) GO TO 200 
  	KELEM=ILAMI(IELMST(LAMBDA))
	ILX=ILAMX(KELEM)

C	FOR EACH STATE:

	DO 100 K=1,6
	DO 100 I=1,5

C	OBTAIN KEYSTATE, RATE STATE, STATE N, NEW NODE:

	IXS=ISX (K)
	ISRATE=I
	N=(I-1)*6+K
	J=(IP-1)*30+N
	PIN=P(IP,N)

C	COMPUTE AND STORE LIKELIHOOD:

	CALL KALFIL (Z,IP,RN,ILX,IXS,KELEM,J,ISRATE,DUR,ILRATE,PIN,LKHDJ)
	LKHD(J)=LKHDJ
	GO TO 100
		
	IF (PIN.LE. 1.E-06) GO TO 100
	PRINT 110,IP,Z,LAMBDA,K,ILRATE,ILRATE,DUR,PIN,LKHDJ,RN
110	FORMAT(1X,I2,1X,F5.3,2X,I3,2X,I1,2X,I2,2X,I2,3X,F5.1,2X,F8.6,2X,
     &F8.4,2X,F8.4)
C	2 F8.4,2X,F8.4)
  
100	CONTINUE
200	RETURN
	END
