	SUBROUTINE NOISE(ZIN,RN,Z)

C
C	THIS SUBROUTINE ESTIMATES THE NOISE POWER IN THE
C	ENVELOPE DETECTED OUTPUT FOR USE BY THE KALMAN
C	FILTERS. AN ESTIMATE OF THE NOISE POWER IS
C	ALSO SUBTRACTED FROM THE ENVELOPE DETECTED SIGNAL
C	IN ORDER TO PRODUCE A ZERO-MEAN NOISE PROCESS
C	AT THE INPUT TO THE MORSE PROCESSOR.
C



	DIMENSION YLONG(200),YSHORT(50)
	DATA YLONG/200*1./
	DATA YSHORT/50*1./
	DATA KL/1/,KKL/1/,KS/1/,KKS/1/
	DATA YMIN1/1./,YMIN2/1./,YMAVG/.05/

	KL=KL+1
	IF(KL .EQ. 201) KL=1
	FS=KS+1
	IF(KS.EQ.51)KS=1
	KKL=KKL+1
	IF(KKL.GE.200) KKL=200
	KKS=KKS+1
	IF (KKS.GE.50)  KKS=50
	
	IF (KKS.LE.2) GO TO 10
	YLONG (KL)=ZIN
	YSHORT (KS)=ZIN
	YMIN1=ZIN
	YMIN2=ZIN

10 	DO 100 I=1,KKL
	IF (YLONG (I).GT.YMIN1) GO TO 100
	YMIN1=YLONG(I)
100	CONTINUE

	DO 200 I=1,KKS
	IF (YSHORT(I).GT.YMIN2) GO TO 200
	YMIN2=YSHORT(I)
200	CONTINUE

	YMIN=YMIN1
	IF (YMIN2.LT.YMIN1) YMIN=YMIN2
	YMAVG=YMAVG+.004* (YMIN-YMAVG)

	RN=0.30*YMAVG
	IF (RN.LT.0.005) RN=0.005
	Z=1.1* (ZIN-2.4*YMAVG-.05)
	
	RETURN
	END


