	SUBROUTINE PROBP(P,PIN,ISAVE,LKHD)

C
C		PROBP COMPUTES THE POSTERIOR PROBABILITY OF EACH NEW PATH
C
C		VARIABLES:
C		P-		INPUT: SAVED PROBS OF PRIOR PATHS

C		OUTPUT:	COMPUTED POSTERIOR PROBS OF NEW PATHS
C		PIN-		INPUT TRANSISTION PROBABILITIES
C		LKHD-		INPUT LIKLIEHOODS OF EACH TRANSTION
C		PSUM-		NORMALIZING CONSTANT (SUM OF P(J))
C

	REAL LKHD
	DIMENSION P(750), PIN(25,30), LKHD(750)
	DIMENSION PSAV(750)	

	PMAX=0.
	PSUM=0.


C	FOR EACH SAVED PATH, EACH TRANSITION:

	DO 100 I=1, ISAVE
	DO 100 N=1,30

C		COMPUTE IDENTITY OF NEW PATH:

	J=(I-1)*30+N

C      PRODUCT OF PROBS, ADD TO PSUM

	PSAV(J)=P(I)*PIN(I,N)*LKHD (J)
	PSUM=PSUM+PSAV(J)

	IF (PSAV(J).LE. PMAX) GO TO 100
	PMAX=PSAV(J)
100	CONTINUE


C		NORMALIZE TO GET PROBABILITIES; SAVE:

	NI=30*ISAVE
	DO 200 J=1,NI
	P(J)=PSAV(J)/PSUM
200	CONTINUE

	RETURN
	END
