	SUBROUTINE SIMSGI(X,SIG)

	COMMON/BLK1/TAU
	COMMON/BLK2/WC,WCHIRP,ASIGMA,BSIGMA,PHISMG, RSIGM,TCHIRP,GAMMA
	DATA XLAST/1./,BETA/1./
	DATA AMP/1./,BFADE/0./,THETA/1./,PHI/1./

	DUR=BETA
	CALL KEY(DUR,X)
	BETA=BETA*(1.-X-XLAST+2.*X*XLAST)+1.
	TK=X*(1.-XLAST)
	XLAST=X

C	CALL RANDN(W,1,0.,ASIGMA)
	AMP=AMP+TK*W
	IF(AMP .LT. 0.01) AMP=.01

C	CALL RANDN(W,1,0.,BSIGMA)
	BFADE=GAMMA*BFADE+W

	AMPB=AMP+BFADE
	IF(AMPB .LT. 0.001) BFADE=0.001-AMP
	AMPB=AMP+BFADE

	TDUR=1000.*TAU*BETA

	WCHRP=X*WCHIRP*EXP(-TDUR/TCHIRP)

	THETA=THETA+(NC+WCHRP)*TAU
	THETA=AMOD(THETA,6.28319)



C	CALL RANDN(W,1,0.,PHISGM)
	PHI=PHI+TK*w
	PHI=AMOD(PHI,6.28319)

	SIG=X*AMPB*SIN(THETA+PHI)
C	CALL RANDN(ZN,1,0.,RSIGM)
	RETURN
	END



