	FUNCTION SPDTR(ISRT,ILRT,ISELM,ILELM)
C
C	THIS FUNCTION RETURNS THE DATA RATE (SPEED) TRANSITION 
C	PROBABILITY BASED ON THE CURRENT ELEM TYPE. THE ALLOWABLE 
C	TRANSITION PROBS ARE STORED IN THE TABLE RTRANS.
C
C	VARIABLES:
C	ISRT	- DATA RATE IDENTITY FOR STATE TO WHICH PATH 
C			IS BEING EXTENDED
C	ILRT	- DATA RATE ON CURRENT PATH 
C	ISELM 	- ELEM TYPE FOR NEXT STATE 
C	ILELM	- ELEM TYPE ON CURRENT PATH 
C

	DIMENSION RTRANS(5,2), MEMPR(6,6), MEMDEL(6,6)
	COMMON /BLKSPD/RTRANS,MEMPR
	COMMON /BLKRAT/MEMDEL

C
C	IF SAVED ELEMENT AND NEW ELEMENT ARE THE SAME 
C	THEN THERE CAN BE NO SPEED CHANGE:
C
	IF (ILELM .NE. ISELM) GO TO 100
	SPDTR = 1.
	IF (ISRT .NE. 3) SPDTR = 0.
	GO TO 300

C
C	OTHERWISE, OBTAIN SPEED TRANSITION PROB
C

100	IDEL=MEMDEL(ILELM,ISELM)
	IND1=MEMPR(ILELM,ISELM)
	IF (IND1 .NE. 0) GOTO 200
	SPDTR = 0.
	GO TO 300

200	IDELSP = (ISRT-3)*IDEL
	SPDTR = RTRANS(ISRT,IND1)
	ISRATE=ILRT+IDELSP
	IF ( ISRATE .GT. 60) SPDTR = 0.
	IF ( ISRATE .LT. 10) SPDTR = 0.

300	RETURN
	END
