	SUBROUTINE TRPROB (IP, LAMBDA, DUR, ILRATE, P)

C	
C		THIS SUBROUTINE COMPUTES THE TRANSITION PROBABILITY
C		FROM SAVED PATH IP TO EACH STATE N AND STORES THE
C		RESULT IN P(IP, N).
C		
C		VARIABLES:
C		IP - INPUT SAVED PATH IDENTITY
C		LAMBDA - INPUT SAVED LTR STATE IDENTITY
C		DUR - INPUT SAVED ELEMENT DURATION
C		ILPATE - INPUT SAVED DATA RATE IDENTITY
C		P - OUTPUT TRANSITION PROBABILITY MATRIX
C	
C		THE FOLLOWING FUNCTION SUBROUTINES ARE USED:
C		XTRANS - RETURNS THE KEYSTATE TRANSITION PROBABILITY
C	               CONDITIONED ON ELEMENT TYPE AND DATA RATE
C		PTRANS - RETURNS THE PATH-CONDITIONAL STATE TRANSITION PROB


	DIMENSION P(25, 30), IELMST (400), ILAMI(16), ILAMX(6)
	DIMENSION PIN(30)
	COMMON  /BLKLAM/IELMST, ILAMI, ILAMX

C	LOOK UP ELEMENT TYPE FOR LTR STATE LAMBDA:

	IF(LAMBDA .NE. 0) GO TO 20

	DO 10 N=1,30
	P(IP,N)=0.
10	CONTINUE
	GO TO 200

20	CONTINUE


C	COMPUTE KEYSTATE TRANSITION PROBABILITY:
	IELEM=ILAMI(IELMST(LAMBDA))
	PTRX=XTRANS(IELEM, DUR, ILRATE)

C	FOR EACH STATE, COMPUTE STATE TRANSITION PROBABILITY:

	PSUM=0.
	DO 100 K=1,6
	DO 100 I=1,5
	N=(1-1)*6+K
	KELM=K
	IRATE=I

	CALL PTRANS(KELM, IRATE, LAMBDA, ILRATE, PTRX, PSUM, PIN, N) 
100	CONTINUE

	DO 300 N=1,30
	P(IP,N)=PIN(N)/PSUM
300	CONTINUE 
200	RETURN 
	END 

